### ISSUE TITLE
Area Buzz ambience space inconsistency

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#1001]
Reporting client info:
```Client Information:
BYOND:515.1635
Key:francinum
```

## Round ID:
209

## Testmerges:
- [Debug reboot failures](https://github.com/DaedalusDock/Gameserver/pull/923)
- [Temporary canRecall fix](https://github.com/DaedalusDock/Gameserver/pull/862)
- [Tgooey Restyle](https://github.com/DaedalusDock/Gameserver/pull/969)
- [Bugs 6.16.24](https://github.com/DaedalusDock/Gameserver/pull/994)
- [Sound tweaks](https://github.com/DaedalusDock/Gameserver/pull/996)
- [Hydroponics change and general QOL](https://github.com/DaedalusDock/Gameserver/pull/998)

## Reproduction:
Standard Station buzz ambience remains when walking into space, but station ambience does not.

**Comment by Kapu1178** [comment]
TM bug, fixed
