### ISSUE TITLE
Pandemic Machine TGUI Panic

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#1012]
Reporting client info:
```Client Information:
BYOND:515.1637
Key:ddanpointman
```

## Round ID:
211

## Testmerges:
- [Debug reboot failures](https://github.com/DaedalusDock/Gameserver/pull/923)
- [Temporary canRecall fix](https://github.com/DaedalusDock/Gameserver/pull/862)
- [Tgooey Restyle](https://github.com/DaedalusDock/Gameserver/pull/969)
- [Advanced cable placement](https://github.com/DaedalusDock/Gameserver/pull/1009)
- [fix bloom the right way](https://github.com/DaedalusDock/Gameserver/pull/1011)
- [Surgery changes and fixes](https://github.com/DaedalusDock/Gameserver/pull/1007)

## Reproduction:
The pandemic machine broke. I was looking at it and the moment i inserted a beaker of blood it bluescreeened. Soemthing abou "Minified React Error #62"

**Comment by francinum** [comment]
@jlsnow301

**Comment by jlsnow301** [comment]
Issue is in Progressbar, which is assigning styles inappropriately. Very tempted to use this as a reason to import tgui-core, since the component does not have that problem there
