### ISSUE TITLE
Disposals kills TOO fast

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#1015]
Reporting client info:
```Client Information:
BYOND:515.1640
Key:myontasm
```

## Round ID:
212

## Testmerges:
- [Debug reboot failures](https://github.com/DaedalusDock/Gameserver/pull/923)
- [Temporary canRecall fix](https://github.com/DaedalusDock/Gameserver/pull/862)
- [Tgooey Restyle](https://github.com/DaedalusDock/Gameserver/pull/969)
- [Ambience tweaks again](https://github.com/DaedalusDock/Gameserver/pull/1014)

## Reproduction:
It turns you into a pulp within a second of stepping inside it. YEOWCH!!

**Comment by francinum** [comment]
Likely addressed by https://github.com/DaedalusDock/daedalusdock/pull/1058
