### ISSUE TITLE
Canary PDA app crashes to bluescreen

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#1016]
Reporting client info:
```Client Information:
BYOND:515.1641
Key:wombat321
```

## Round ID:
213

## Testmerges:
- [Debug reboot failures](https://github.com/DaedalusDock/Gameserver/pull/923)
- [Temporary canRecall fix](https://github.com/DaedalusDock/Gameserver/pull/862)
- [Tgooey Restyle](https://github.com/DaedalusDock/Gameserver/pull/969)
- [Ambience tweaks again](https://github.com/DaedalusDock/Gameserver/pull/1014)

## Reproduction:
Upon downloading and using the PDA app "canary" my pda went into bluescreen and was frozen until the evac shuttle arrived.

**Comment by francinum** [comment]
Insufficient Information.
