### ISSUE TITLE
Body says "catatonic" or "no soul" when examined even with an active player ghost inhabiting it

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#1049]
Reporting client info:
```Client Information:
BYOND:515.1640
Key:myontasm
```

## Round ID:
231

## Testmerges:
- [Debug reboot failures](https://github.com/DaedalusDock/Gameserver/pull/923)
- [Temporary canRecall fix](https://github.com/DaedalusDock/Gameserver/pull/862)
- [Tgooey Restyle](https://github.com/DaedalusDock/Gameserver/pull/969)
- [Makes IDs more consistent](https://github.com/DaedalusDock/Gameserver/pull/1029)
- [Small bug fixes](https://github.com/DaedalusDock/Gameserver/pull/1046)
- [Small tweak to examine](https://github.com/DaedalusDock/Gameserver/pull/1045)

## Reproduction:
Fake descriptions fooling doctors into believing you are permadead for some ungodly reason.

**Comment by Kapu1178** [comment]
Cannot reproduce.

**Comment by Kapu1178** [comment]
i fixed this
