### ISSUE TITLE
Cargo shuttle cannot arrive with cargo onboard

### ISSUE THREAD

**Issue by francinum** [DaedalusDock/daedalusdock#149]
## Testmerges:
[#135: 'intercoms are off roundstart' by Kapu1178 at commit 2c1f87f11e](https://github.com/DaedalusDock/Gameserver/pull/135)
[#132: 'TGUI corners are now sharp by default' by francinum at commit 57ae493b56](https://github.com/DaedalusDock/Gameserver/pull/132)
[#131: 'Adds Trolleys to Cargo' by FunnyLegJiggle at commit af03ae8248](https://github.com/DaedalusDock/Gameserver/pull/131)
[#125: '"Nerf" aurora c' by Kapu1178 at commit 3a4e46e498](https://github.com/DaedalusDock/Gameserver/pull/125)
[#67: 'Kapuconomy' by Kapu1178 at commit 3212c28374](https://github.com/DaedalusDock/Gameserver/pull/67)
[#115: 'Volume pumps use pump_gas, power meter in pump UI, and valve sprite edit + sounds (also removes passive gates)' by Spyroshark at commit dc39736835](https://github.com/DaedalusDock/Gameserver/pull/115)
[#100: 'Inflatable Shelters (plus a sprite for the inflatables case)' by Spyroshark at commit c284a2dd9c](https://github.com/DaedalusDock/Gameserver/pull/100)
[#138: 'Baystation Wounds Port' by Kapu1178 at commit 65409f594f](https://github.com/DaedalusDock/Gameserver/pull/138)
[#137: 'RMB Actions for sticky tape' by Cenrus at commit 9e23002732](https://github.com/DaedalusDock/Gameserver/pull/137)
[#147: 'Speed up the roundstart significantly' by Kapu1178 at commit 736ad6885d](https://github.com/DaedalusDock/Gameserver/pull/147)
[#146: 'Ghosts take on their parent appearance' by Kapu1178 at commit 6bf8055bad](https://github.com/DaedalusDock/Gameserver/pull/146)
[#145: 'Adjustments to text stacking' by Kapu1178 at commit a8f06dd623](https://github.com/DaedalusDock/Gameserver/pull/145)
[#144: 'Fix teshari feathers not using hair color' by Kapu1178 at commit bd8edcb4c7](https://github.com/DaedalusDock/Gameserver/pull/144)
[#143: 'Small fixes to the wall lighting overlays' by francinum at commit e45a14a996](https://github.com/DaedalusDock/Gameserver/pull/143)
[#119: 'low effort initialize optimizations' by Kapu1178 at commit 6f925b1ab4](https://github.com/DaedalusDock/Gameserver/pull/119)
[#134: 'Adds a groan tube (IMPORTANT)' by Spyroshark at commit b62681db64](https://github.com/DaedalusDock/Gameserver/pull/134)

## Reproduction:
Attempt to bring the cargo shuttle to the station with cargo onboard, be it mail, or an order. Taking the crates off the shuttle allows the shuttle to dock. Likely an issue with anti-abuse checks.

**Comment by Kapu1178** [comment]
fixed
