### ISSUE TITLE
Low wall smoothing broken

### ISSUE THREAD

**Issue by Cenrus** [DaedalusDock/daedalusdock#151]
![image](https://user-images.githubusercontent.com/31044876/213952428-36899e67-8155-434d-96f2-d5df0247f29a.png)
moth for reference
only happens when blast doors are involved, otherwise the smoothing is fine

**Comment by francinum** [comment]
Known issue. Unsure of the best way to deal with it in honesty. Also the reason that the engineering airlock looks really, really weird.
