### ISSUE TITLE
AI has motherdrone as a default lawset

### ISSUE THREAD

**Issue by Cenrus** [DaedalusDock/daedalusdock#152]
`Round ID 95/96? - They didn't add it in their report -francinum`

Recently received motherdrone as a default lawset as a latejoin AI. I suggest this is removed because it prevents the AI from doing anything outside of repairing the station without even being able to say a word.

**Comment by francinum** [comment]
Production config has `DEFAULT_LAWS 0`, This is... Concerning if it's true.

**Comment by francinum** [comment]
Cannot reproduce.
