### ISSUE TITLE
Surgeries Wonky

### ISSUE THREAD

**Issue by Xerkie** [DaedalusDock/daedalusdock#153]
## Testmerges:

https://github.com/DaedalusDock/Gameserver/pull/135
https://github.com/DaedalusDock/Gameserver/pull/132
https://github.com/DaedalusDock/Gameserver/pull/131
https://github.com/DaedalusDock/Gameserver/pull/125
https://github.com/DaedalusDock/Gameserver/pull/67
https://github.com/DaedalusDock/Gameserver/pull/115
https://github.com/DaedalusDock/Gameserver/pull/100
https://github.com/DaedalusDock/Gameserver/pull/138
https://github.com/DaedalusDock/Gameserver/pull/137
https://github.com/DaedalusDock/Gameserver/pull/147
https://github.com/DaedalusDock/Gameserver/pull/146
https://github.com/DaedalusDock/Gameserver/pull/145
https://github.com/DaedalusDock/Gameserver/pull/144
https://github.com/DaedalusDock/Gameserver/pull/143
https://github.com/DaedalusDock/Gameserver/pull/119
https://github.com/DaedalusDock/Gameserver/pull/134

## Reproduction:

Surgery steps seem to be wonky. When doing surgeries like Organ Manipulation on the arms, on the last step before insertion where you're supposed to make an additional incision, it'll tell you to make the incision, but due to surgical wounds, the already existing incision will be 'large enough', and the step will be skipped right after, letting you proceed with the surgery.

Also, sometimes when doing surgeries, it'll get stuck repeating the same steps ad infinitum, with there being no way to break this loop, not even restarting the surgery, effectively locking you out of being able to ever do the next step of the surgery. Happened with the last step of eyes organ manipulation and with the retractor step of prosthetic replacement.

**Comment by Kapu1178** [comment]
Needs reproduction steps.

**Comment by Xerkie** [comment]
> Needs reproduction steps.

Happened again in the most recent round when attempting to replace someones' amputated limbs. It seems limb replacement surgery is just busted.

**Comment by Kapu1178** [comment]
Bug identified as an issue with how TG does surgery on bodyparts that dont exist
