### ISSUE TITLE
Player ghosts will appear invisible if the cause of death destroyed the body.

### ISSUE THREAD

**Issue by myontasm** [DaedalusDock/daedalusdock#156]
## Testmerges:

#146 

## Reproduction:

You can achieve this by getting killed in a manner that removes any trace of body and limbs, such as getting killed by a Legion skull in Lavaland or any other way that would absolutely obliterate you.

**Comment by myontasm** [comment]
should be noted this is a consequence of the feature working far too well 
![WILD DOG](https://user-images.githubusercontent.com/10575508/214114146-a3bef6a2-71ce-417b-9b31-096e2e7d3409.jpg)

**Comment by Kapu1178** [comment]
funny

**Comment by Kapu1178** [comment]
Fixed
