### ISSUE TITLE
Cargo shuttle not docking

### ISSUE THREAD

**Issue by mcmeiler** [DaedalusDock/daedalusdock#166]
Reporting client version: 514.1584

## Round ID:
98

## Testmerges:

**Unknown** (to me). `show-server-revision` broke during this round.

## Reproduction:

1. Order crates
2. Send shuttle to cargo
3. Shuttle refuses to dock, timer jumps from 0 to 2.
4. Repeat.

**Comment by Kapu1178** [comment]
fixed
