### ISSUE TITLE
Vox Spawn with Two internals, One is nowhere to be found

### ISSUE THREAD

**Issue by Rak-Sulavin** [DaedalusDock/daedalusdock#187]
## Round ID:
103, Current Round

## Reproduction:
Apprears to be produced by just joining the game when the round starts as a Vox. Staff told me to make an issue regarding this.

![7b38c835b4b0e1ce278e6e7d8ef23aa8](https://user-images.githubusercontent.com/101994875/216716096-f25f4560-5d68-4b2d-b374-bc07ce928241.png)

**Comment by Kapu1178** [comment]
What a peculiar little bug
