### ISSUE TITLE
Invisible Holosigns

### ISSUE THREAD

**Issue by bluezorua** [DaedalusDock/daedalusdock#221]
## Testmerges:[#163: 'QM no longer a head, CMO > Medical Director, job title tweaks' by Kapu1178 at commit 6ff28bb2f3](https://github.com/DaedalusDock/Gameserver/pull/163)
[#197: 'ZAS: At The Speed of Light' by Kapu1178 at commit b468f31b62](https://github.com/DaedalusDock/Gameserver/pull/197)
[#138: 'Baystation Wounds Port' by Kapu1178 at commit 02d2dae120](https://github.com/DaedalusDock/Gameserver/pull/138)
[#209: 'Removes Field of View and returns everything to the GAME_PLANE' by Kapu1178 at commit 0fda862f16](https://github.com/DaedalusDock/Gameserver/pull/209)
[#212: 'Health Analyzer chem scanner rightclick purge' by francinum at commit ad5a4f4bd0](https://github.com/DaedalusDock/Gameserver/pull/212)
[#211: 'Base TGUI theme brightening' by francinum at commit 092ca491dc](https://github.com/DaedalusDock/Gameserver/pull/211)

## Reproduction:
get a holographic sign projector
click on a tile
wait for the do_after to complete
use your eyes

![image](https://user-images.githubusercontent.com/54711687/219490565-b5efeae6-c1ae-4bee-b9cd-8ea84ef975e0.png)
![image](https://user-images.githubusercontent.com/54711687/219490583-3baa9c2b-d82c-4cef-b513-7bb856a1334c.png)
![image](https://user-images.githubusercontent.com/54711687/219490643-5295d026-504c-437f-93e9-9c7599256a9c.png)

**Comment by Kapu1178** [comment]
Issue found and fixed, related pr attached.
