### ISSUE TITLE
All Security members are assigned to the same department

### ISSUE THREAD

**Issue by chesse20** [DaedalusDock/daedalusdock#231]
## Round ID: 
112

## Reproduction:
Join as security officer, get assigned to the same department as other security officers.
This has happened in multiple rounds where sec officers were assigned to the same department even with only 2 sec officers

**Comment by francinum** [comment]
This appears to be intentional?? According to the rewritten algorithm, it'll try to keep officers in groups of at least two?

I believe this is operating as intentional, especially with only two officers.
