### ISSUE TITLE
Security Camera Console not functioning on working cameras

### ISSUE THREAD

**Issue by chesse20** [DaedalusDock/daedalusdock#233]
## Round ID:
112

## Testmerges:
#208 #212 #219 #224 

## Reproduction:

Use security camera to look at specific areas, all cameras in the area won't work but when going up to the cameras they are functioning/not cut

3 functional library cameras: 
![dreamseeker_tSX2Mzlm7X](https://user-images.githubusercontent.com/9161779/220496811-7c869dea-ee3c-400f-9182-fee5b72b5f83.png)

None of the library cameras display any footage as if broken:
![bmSlz6RYOT](https://user-images.githubusercontent.com/9161779/220496837-73118b04-20ef-42b9-8471-13848877db92.png)

**Comment by Kapu1178** [comment]
hnnnnn
