### ISSUE TITLE
Newly placed walls glitch

### ISSUE THREAD

**Issue by chesse20** [DaedalusDock/daedalusdock#291]
## Round ID:
125

## Testmerges:
[#241: 'Griddle QoL changes + Spatula' by FunnyLegJiggle at commit 034a088822](https://github.com/DaedalusDock/Gameserver/pull/241)
#265
#266:
#275
#274
#214
#288
#289

## Reproduction:

Place girder in hallway, put metal onto it, make a new wall
![dreamseeker_VTh8dH8a6x](https://user-images.githubusercontent.com/9161779/229934089-ebe1eac4-3ee8-4a62-b1c8-70040130bb91.png)
wall lighting is broken

**Comment by Kapu1178** [comment]
Testmerge issue, probably fixed?
