### ISSUE TITLE
Me arguing why scibags should pick up slime extracts again

### ISSUE THREAD

**Issue by MitztheKat** [DaedalusDock/daedalusdock#292]
I think kapu forgor the fact that crossbreeding exists
I was contemplating this in my dreams last night, and although I screamed at you in my dreams and then you tried to get my execution in-game (that shift where the cap'n was tot & I was JAKET probably traumatized me to dream about it) I think we can discuss this peacefully.
Some options:
make scibags undumpable
make crossbreeds only take 5 extracts
make slime reactions all on a global cooldown (some form of space-time flux makes the slime extract peter out) like 1 or 2 seconds cooldown tops
tell me if any of these sound appealing on how to deal with the slime extract conundrum (TM)

**Comment by Kapu1178** [comment]
cross breeds are dumb stupid and shouldnt exist in the first place
