### ISSUE TITLE
Modsuit Pathfinding Module broken

### ISSUE THREAD

**Issue by Sylphily** [DaedalusDock/daedalusdock#303]
## Testmerges:
does not apply,
## Reproduction:
get a mod suit, use pathfinder module, go across a door that is closed activate and it will open the door, but will stop before it can open and go through

AKA stupid bot AI will not wait for the door to open!

**Comment by Admiral-Gigaton** [comment]
aint no server in existance touched pathfinder modules, not /tg/, not splurt, not monke, and it seems not even daedalus. pathfinders are a really shitty gimmick item, i used it once for real as a wrestling champion gimmick, i would recall my ai modsuit and yell "MODSUIT MANN!!" as it powered up. i was robust enough to make it to the semifinals but some crackhead with chairs turned my skull into a bowl (i was running the RD modsuit so it makes sense, shitty armor)

**Comment by Sylphily** [comment]
since here it says that it is fixed, should this then be closed

https://discord.com/channels/997284596657954877/1058633263519903764/1217665651251085362
