### ISSUE TITLE
Sprinting doesn't work in command mode

### ISSUE THREAD

**Issue by gonenoculer5** [DaedalusDock/daedalusdock#357]
Reporting client version: 514.1589
## Round ID:
140

## Testmerges:
- [Movables call Entered(src) post initialize()](https://github.com/DaedalusDock/Gameserver/pull/296)
- [[TM ONLY] Remove inactive modsuit slowdown, reduce active slowdown on a number of suits](https://github.com/DaedalusDock/Gameserver/pull/320)
- [Fix Pack 3: Revenge Of The Fuck](https://github.com/DaedalusDock/Gameserver/pull/225)
- [HTML PREFS: DIE TGUI DIE](https://github.com/DaedalusDock/Gameserver/pull/330)
- [Stamina Refactor + Gooncrit](https://github.com/DaedalusDock/Gameserver/pull/342)
- [Daedalus Meta](https://github.com/DaedalusDock/Gameserver/pull/345)
- [Revert airlock controller UI to HTML](https://github.com/DaedalusDock/Gameserver/pull/331)
- [Reagent Description and Abstract Changes](https://github.com/DaedalusDock/Gameserver/pull/164)
- [Lighting Redux: Second Impact](https://github.com/DaedalusDock/Gameserver/pull/353)

## Reproduction:
Be in a situation that requires sprinting
Press shift to sprint in command mode
Whoops, no gas.

**Comment by Kapu1178** [comment]
BYOND bug
