### ISSUE TITLE
Scrubbers set to Siphon always sleep

### ISSUE THREAD

**Issue by Spyroshark** [DaedalusDock/daedalusdock#358]
Reporting client version: 514.1583

## Round ID:
140

## Testmerges:
- [Movables call Entered(src) post initialize()](https://github.com/DaedalusDock/Gameserver/pull/296)
- [[TM ONLY] Remove inactive modsuit slowdown, reduce active slowdown on a number of suits](https://github.com/DaedalusDock/Gameserver/pull/320)
- [Fix Pack 3: Revenge Of The Fuck](https://github.com/DaedalusDock/Gameserver/pull/225)
- [HTML PREFS: DIE TGUI DIE](https://github.com/DaedalusDock/Gameserver/pull/330)
- [Stamina Refactor + Gooncrit](https://github.com/DaedalusDock/Gameserver/pull/342)
- [Daedalus Meta](https://github.com/DaedalusDock/Gameserver/pull/345)
- [Revert airlock controller UI to HTML](https://github.com/DaedalusDock/Gameserver/pull/331)
- [Reagent Description and Abstract Changes](https://github.com/DaedalusDock/Gameserver/pull/164)
- [Lighting Redux: Second Impact](https://github.com/DaedalusDock/Gameserver/pull/353)

## Reproduction:

Set the mode on scrubbers to "siphon" on an air alarm
look at it with your eyes
see that it is green

![image](https://github.com/DaedalusDock/daedalusdock/assets/35285914/746c35ab-fddf-4418-97fc-5464d1cf1797)
![image](https://github.com/DaedalusDock/daedalusdock/assets/35285914/9cb522df-c2cb-496e-8677-c61667a12e21)

**Comment by Kapu1178** [comment]
TG Scrubbers for some reason will not scrub if there is more than 50 atmospheres of pressure in the given room. I removed this in the linked PR.
