### ISSUE TITLE
walking by a deliveries chute will dislocate your camera from your body

### ISSUE THREAD

**Issue by bluezorua** [DaedalusDock/daedalusdock#368]
Reporting client version: 514.1589

## Round ID:
142

## Testmerges:
- [[TM ONLY] Remove inactive modsuit slowdown, reduce active slowdown on a number of suits](https://github.com/DaedalusDock/Gameserver/pull/320)
- [Revert airlock controller UI to HTML](https://github.com/DaedalusDock/Gameserver/pull/331)
- [Lighting Redux: Second Impact](https://github.com/DaedalusDock/Gameserver/pull/353)
- [The Little Boy To Speed's Fatman](https://github.com/DaedalusDock/Gameserver/pull/367)
- [Removes lavaland mob gun/thrown damage reduction (balance change)](https://github.com/DaedalusDock/Gameserver/pull/365)
- [mapped mouse spawns, plus a new infestation event](https://github.com/DaedalusDock/Gameserver/pull/364)
- [Balance Changes](https://github.com/DaedalusDock/Gameserver/pull/363)
- [Speech improvements](https://github.com/DaedalusDock/Gameserver/pull/351)
- [Allow lone op disk nag to be disabled](https://github.com/DaedalusDock/Gameserver/pull/349)

## Reproduction:
be on metastation
walk past the plastic sheet labeled "service deliveries" in main cargo
you need to open up the glass windoors but not physically entered
walk around and realise your not moving your camera

note that it is _very_ inconsistent

**Comment by Kapu1178** [comment]
This exposed a critical issue in movecode, which was fun. Thankfully, a patch isn't hard.
