### ISSUE TITLE
Fabricators don't change icons when working, then permanently change to working icon

### ISSUE THREAD

**Issue by Spyroshark** [DaedalusDock/daedalusdock#380]
Reporting client version: 514.1589

## Round ID:
150

![image](https://github.com/DaedalusDock/daedalusdock/assets/35285914/27790235-91a0-434f-91e2-1938b775a5a9)

this is a current live round and i have broken IC OOC rules by posting this

## Testmerges:
- [[TM ONLY] Remove inactive modsuit slowdown, reduce active slowdown on a number of suits](https://github.com/DaedalusDock/Gameserver/pull/320)
- [Lighting Redux: Second Impact](https://github.com/DaedalusDock/Gameserver/pull/353)
- [Removes lavaland mob gun/thrown damage reduction (balance change)](https://github.com/DaedalusDock/Gameserver/pull/365)
- [mapped mouse spawns, plus a new infestation event](https://github.com/DaedalusDock/Gameserver/pull/364)
- [nuclear bomb in PR form](https://github.com/DaedalusDock/Gameserver/pull/283)
- [Verb Man4g3r](https://github.com/DaedalusDock/Gameserver/pull/337)
- [ZAS Optimizations and Improvements](https://github.com/DaedalusDock/Gameserver/pull/378)
- [The Lobby now has a Job Estimation list](https://github.com/DaedalusDock/Gameserver/pull/377)
- [Fix headharddel](https://github.com/DaedalusDock/Gameserver/pull/379)

## Reproduction:

walk up to fabricator
print something
fabricator doesn't do it's sprite change until after then stays that way
print something again and it will STOP showing the "fabricating" sprite

**Comment by Kapu1178** [comment]
fixed in #379
