### ISSUE TITLE
some robot parts display their limb sprite and item sprite at the same time

### ISSUE THREAD

**Issue by Spyroshark** [DaedalusDock/daedalusdock#381]
Reporting client version: 514.1589

## Round ID:
150

this is what ONE robot left leg looks like. no other items are on the tile.
![image](https://github.com/DaedalusDock/daedalusdock/assets/35285914/48f00a73-40d3-4a84-88a6-10ed1ee1e703)

## Testmerges:
- [[TM ONLY] Remove inactive modsuit slowdown, reduce active slowdown on a number of suits](https://github.com/DaedalusDock/Gameserver/pull/320)
- [Lighting Redux: Second Impact](https://github.com/DaedalusDock/Gameserver/pull/353)
- [Removes lavaland mob gun/thrown damage reduction (balance change)](https://github.com/DaedalusDock/Gameserver/pull/365)
- [mapped mouse spawns, plus a new infestation event](https://github.com/DaedalusDock/Gameserver/pull/364)
- [nuclear bomb in PR form](https://github.com/DaedalusDock/Gameserver/pull/283)
- [Verb Man4g3r](https://github.com/DaedalusDock/Gameserver/pull/337)
- [ZAS Optimizations and Improvements](https://github.com/DaedalusDock/Gameserver/pull/378)
- [The Lobby now has a Job Estimation list](https://github.com/DaedalusDock/Gameserver/pull/377)
- [Fix headharddel](https://github.com/DaedalusDock/Gameserver/pull/379)

## Reproduction:

print "Cyborg Left Leg"
there is now an icon of a left leg limb and a cyborg RIGHT leg ????

**Comment by francinum** [comment]
Fixed ages ago.
