### ISSUE TITLE
Experiments button on Surgery Computer has no purpose with Experisci removed.

### ISSUE THREAD

**Issue by gonenoculer5** [DaedalusDock/daedalusdock#392]
Reporting client version: 514.1589

## Round ID:
153

## Testmerges:
- [[TM ONLY] Remove inactive modsuit slowdown, reduce active slowdown on a number of suits](https://github.com/DaedalusDock/Gameserver/pull/320)
- [Lighting Redux: Second Impact](https://github.com/DaedalusDock/Gameserver/pull/353)
- [ZAS Optimizations and Improvements](https://github.com/DaedalusDock/Gameserver/pull/378)
- [Augments Tab](https://github.com/DaedalusDock/Gameserver/pull/387)
- [TOTAL PLUMBING DEATH. MAXIMUM CYTOLOGY KILL.](https://github.com/DaedalusDock/Gameserver/pull/376)
- [Fix a couple bugs](https://github.com/DaedalusDock/Gameserver/pull/385)
- [Inflatable Shelters (plus a sprite for the inflatables case)](https://github.com/DaedalusDock/Gameserver/pull/100)
- [Speed and Bugfix ports](https://github.com/DaedalusDock/Gameserver/pull/388)
- [darken wall paint](https://github.com/DaedalusDock/Gameserver/pull/390)
- [Trolleys can be rotated on altclick](https://github.com/DaedalusDock/Gameserver/pull/389)
- [Adds feral hogs, maint slugs, and replaces the HOS and janitor's pets](https://github.com/DaedalusDock/Gameserver/pull/386)

## Reproduction:
Open surgery computer. Click experiments.

**Comment by francinum** [comment]
What surgery computer
