### ISSUE TITLE
Chargen loadout colors only display on Teshari

### ISSUE THREAD

**Issue by CliffracerX** [DaedalusDock/daedalusdock#393]
## Testmerges:

[#320: '[TM ONLY] Remove inactive modsuit slowdown, reduce active slowdown on a number of suits' by Kapu1178 at commit e5eb14c61d](https://github.com/DaedalusDock/Gameserver/pull/320)
[#353: 'Lighting Redux: Second Impact' by Kapu1178 at commit b5a69dea75](https://github.com/DaedalusDock/Gameserver/pull/353)
[#378: 'ZAS Optimizations and Improvements' by Kapu1178 at commit 81aa2ceeb2](https://github.com/DaedalusDock/Gameserver/pull/378)
[#387: 'Augments Tab' by Kapu1178 at commit 2053609268](https://github.com/DaedalusDock/Gameserver/pull/387)
[#376: 'TOTAL PLUMBING DEATH. MAXIMUM CYTOLOGY KILL.' by Kapu1178 at commit ed289a7977](https://github.com/DaedalusDock/Gameserver/pull/376)
[#385: 'Fix a couple bugs' by Kapu1178 at commit 95b59de15f](https://github.com/DaedalusDock/Gameserver/pull/385)
[#100: 'Inflatable Shelters (plus a sprite for the inflatables case)' by Spyroshark at commit bc4a1cbf2c](https://github.com/DaedalusDock/Gameserver/pull/100)
[#388: 'Speed and Bugfix ports' by Kapu1178 at commit c8f1c8936f](https://github.com/DaedalusDock/Gameserver/pull/388)
[#390: 'darken wall paint' by Kapu1178 at commit 541ac4c2af](https://github.com/DaedalusDock/Gameserver/pull/390)
[#389: 'Trolleys can be rotated on altclick' by FunnyLegJiggle at commit df91ee8091](https://github.com/DaedalusDock/Gameserver/pull/389)
[#386: 'Adds feral hogs, maint slugs, and replaces the HOS and janitor's pets' by Spyroshark at commit bec0dd8611](https://github.com/DaedalusDock/Gameserver/pull/386)

## Reproduction:

Go to character editor, make a Teshari character, and give them a loadout item with color customization options.  Customize color, see color displayed in Loadout preview.  Do the same on a regular humanoid character like Vox or similar; no preview.  This applies to both hue-shiftable items and advanced color items.

**Comment by Kapu1178** [comment]
Could not reproduce
