### ISSUE TITLE
Detective's gun has broken sprites.

### ISSUE THREAD

**Issue by DreadedReborn** [DaedalusDock/daedalusdock#405]
## Round ID:
154

Detective's gun variants are missing their textures, and default to placeholder gun textures.
![image](https://github.com/DaedalusDock/daedalusdock/assets/8942901/5c6227e7-deec-4268-9d2f-fed3f6f14696)
![image](https://github.com/DaedalusDock/daedalusdock/assets/8942901/5f4334f3-7f17-46d5-97a3-391ff5ea5a86)

## Testmerges:
[#320: '[TM ONLY] Remove inactive modsuit slowdown, reduce active slowdown on a number of suits' by Kapu1178 at commit e5eb14c61d](https://github.com/DaedalusDock/Gameserver/pull/320)
[#353: 'Lighting Redux: Second Impact' by Kapu1178 at commit b5a69dea75](https://github.com/DaedalusDock/Gameserver/pull/353)
[#100: 'Inflatable Shelters (plus a sprite for the inflatables case)' by Spyroshark at commit bc4a1cbf2c](https://github.com/DaedalusDock/Gameserver/pull/100)
[#386: 'Adds feral hogs, maint slugs, and replaces the HOS and cargo's pets' by Spyroshark at commit 36eb11741d](https://github.com/DaedalusDock/Gameserver/pull/386)
[#402: 'Fixes a ton of circuitboards being unobtainable' by Kapu1178 at commit eeaa5df591](https://github.com/DaedalusDock/Gameserver/pull/402)
[#399: 'Fix circulators getting "stuck" if the output was a vacuum.' by Kapu1178 at commit c0e794fc8a](https://github.com/DaedalusDock/Gameserver/pull/399)
[#398: 'fix zombie hands' by Kapu1178 at commit 05af28b203](https://github.com/DaedalusDock/Gameserver/pull/398)
[#397: 'Some balance stuff' by Kapu1178 at commit 2655a15e4f](https://github.com/DaedalusDock/Gameserver/pull/397)
[#396: 'rebalance softcrit/oxyloss' by Kapu1178 at commit 75bbdff79e](https://github.com/DaedalusDock/Gameserver/pull/396)
[#395: 'Baystation Gunpoint' by Kapu1178 at commit d0010051be](https://github.com/DaedalusDock/Gameserver/pull/395)
[#394: 'Fix Transformations ghosting the user and minor sprite issue.' by Kapu1178 at commit db074d4642](https://github.com/DaedalusDock/Gameserver/pull/394)
[#401: 'Calling in OB on Drifting Contractor' by Kapu1178 at commit 02ee7c23cf](https://github.com/DaedalusDock/Gameserver/pull/401)
[#400: 'The Melberting' by Kapu1178 at commit f59d06df57](https://github.com/DaedalusDock/Gameserver/pull/400)
[#403: 'Felinid Removal 2023' by Kapu1178 at commit 90b4b49e49](https://github.com/DaedalusDock/Gameserver/pull/403)
[#404: 'Biobags hold extracts' by Cenrus at commit bb9b224145](https://github.com/DaedalusDock/Gameserver/pull/404)

## Reproduction:
Attempt to change the Detective's handgun texture via it's ingame customization menu.
Watch it turn into a purple-black missing texture gun.

**Comment by francinum** [comment]
Modular Content issues.

**Comment by Kapu1178** [comment]
Fixed
