### ISSUE TITLE
Cargo loan syndicates never arrived 

### ISSUE THREAD

**Issue by Cenrus** [DaedalusDock/daedalusdock#406]
## Testmerges:

Can't post it all on mobile but check Dudleys post in #watchdog

## Reproduction:

Loan shuttle when centcom asks you to allow the syndicate to hijack the cargo shuttle and wait for it to arrive.

Check the shuttle expecting them to be there, but there is nothing. The console seems to permanently be stuck as "loaned" from here on

**Comment by francinum** [comment]
Old and unreplicated.
