### ISSUE TITLE
Medical Issues

### ISSUE THREAD

**Issue by Xerkie** [DaedalusDock/daedalusdock#450]
## Reproduction:
There aren't any Fix-O-Veins/Vascular Recouplers in Medical excluding in the special first aid kits Doctors get when they spawn, and there are no medbelts. You can buy spare medbelts from the machine, but they cost 200CR each and there's only two of them.

Vascular Recouplers don't fit in the medbelt.

It appears you can't Splint somebody with a bandaged limb

If you use gauze on a sink to try and wash it, you rip it up to turn it into a damp rag (may be intentional)

The Blood Filter appears to have no use

The Bodyscanner does not display organ damage accurately. Two patients had failing organ sets, but the bodyscanner reported all organs functional

The handheld medical scanner does not show medical reagents like multiver or epinephrine inside people (may be intentional)

Cyberhearts vanish when being inserted into somebody

If you try to forcefeed a pill to somebody who's on the ground, you instead do a dental implant on them, as there's no prerequisite step to dental implant surgery anymore

Sleeping causes you to gain BRUTE/BURN damage as though you were in crit.

(Nonmedical) You can't bottlesmash over peoples' heads anymore. I tried to smash a vodka bottle into a Teshari's head and all it did was forcefeed them, in both combat and noncombat modes. Please urgently fix, I need to break Teshari skulls.

**Comment by Kapu1178** [comment]
all mostly fixes
