### ISSUE TITLE
Riot helmet flashlight / icon issue

### ISSUE THREAD

**Issue by blackwolf602** [DaedalusDock/daedalusdock#485]
Round ID: Private test

Reproduction:
/obj/item/clothing/head/helmet/riot attempt to apply flashlight, unable to do to it

it requires a "can_flashlight = TRUE" added in code to it but when added that created a new issue involving icon switching between flashlight and non flashlight state when you 1. toggle light, 2. flip helmet up 3. flip helmet down (flashlight icon is now gone)

**Comment by francinum** [comment]
That's... The exact reason you aren't allowed to put a flashlight on them.
