### ISSUE TITLE
Organ repair surgery can be done on a closed chest

### ISSUE THREAD

**Issue by Spyroshark** [DaedalusDock/daedalusdock#490]
Reporting client version: 514.1589

## Round ID:
161

## Testmerges:
- [Saves more init time + fixes a minor SSshuttle bug](https://github.com/DaedalusDock/Gameserver/pull/445)
- [Automatic Input Redirection](https://github.com/DaedalusDock/Gameserver/pull/458)
- [Fixes verb scope on Look Upwards](https://github.com/DaedalusDock/Gameserver/pull/475)
- [Kapuchem](https://github.com/DaedalusDock/Gameserver/pull/462)
- [Remove New() uses in atmospherics equipment](https://github.com/DaedalusDock/Gameserver/pull/457)
- [Fixes a decade old ZAS issue](https://github.com/DaedalusDock/Gameserver/pull/483)

## Reproduction:

Go to a guy with organ damage, aim for the chest, then use a brute pack. It opens up the menu to select an organ to patch up despite the fact that you shouldn't(?) have access to them. When this happened the guy also had brute damage on the chest which I was trying (and failing) to heal.

**Comment by Kapu1178** [comment]
Fixed in link PR
