### ISSUE TITLE
Report Issue button does not work

### ISSUE THREAD

**Issue by Spyroshark** [DaedalusDock/daedalusdock#530]
## Testmerges:
[#445: 'Saves more init time + fixes a minor SSshuttle bug' by Kapu1178 at commit e2b9c35c00](https://github.com/DaedalusDock/Gameserver/pull/445)
[#500: 'adds the Voice Changer and more' by Kapu1178 at commit 62e5822486](https://github.com/DaedalusDock/Gameserver/pull/500)
[#505: 'Click-Drag can now be used to consistently manipulate inventories.' by Kapu1178 at commit 41786801f5](https://github.com/DaedalusDock/Gameserver/pull/505)
[#501: 'LITD Fixes' by Kapu1178 at commit 58cfcf943c](https://github.com/DaedalusDock/Gameserver/pull/501)
[#498: 'Use rust_g over byond file write for dynamic setup' by Kapu1178 at commit 446f037ef8](https://github.com/DaedalusDock/Gameserver/pull/498)
[#432: 'Bump rust-g, fix config_error' by francinum at commit 7931dd770c](https://github.com/DaedalusDock/Gameserver/pull/432)
[#508: 'Small tweak to phone icon state handling' by francinum at commit 93ad0d97b9](https://github.com/DaedalusDock/Gameserver/pull/508)
[#524: 'fixes ambience' by Kapu1178 at commit e442c5fb96](https://github.com/DaedalusDock/Gameserver/pull/524)
[#523: 'Brainmed' by Kapu1178 at commit 601bd5490c](https://github.com/DaedalusDock/Gameserver/pull/523)
[#521: 'pressure damage now hurts your ears and eyes' by Kapu1178 at commit 0595db0370](https://github.com/DaedalusDock/Gameserver/pull/521)
[#525: 'Better stack trace code for DCS related things' by Kapu1178 at commit e98016c4f4](https://github.com/DaedalusDock/Gameserver/pull/525)

## Reproduction:
click the "report issue button"
get the tgui crash error :(

![image](https://github.com/DaedalusDock/daedalusdock/assets/35285914/8854cec6-c851-4ade-9939-64f6deaa045a)

(no idea what caused this, but maybe the crash info here will help?)

**Comment by Spyroshark** [comment]
the irony of opening a bug report on the bug reporter is not lost on me by the way

**Comment by Kapu1178** [comment]
@francinum

**Comment by francinum** [comment]
fixed by #528
