### ISSUE TITLE
Making a Spike Head creates copies of your head when you take them down

### ISSUE THREAD

**Issue by Jedi-Toothpaste** [DaedalusDock/daedalusdock#532]
## Testmerges:
[#445: 'Saves more init time + fixes a minor SSshuttle bug' by Kapu1178 at commit e2b9c35c00](https://github.com/DaedalusDock/Gameserver/pull/445)
[#500: 'adds the Voice Changer and more' by Kapu1178 at commit 62e5822486](https://github.com/DaedalusDock/Gameserver/pull/500)
[#505: 'Click-Drag can now be used to consistently manipulate inventories.' by Kapu1178 at commit 41786801f5](https://github.com/DaedalusDock/Gameserver/pull/505)
[#501: 'LITD Fixes' by Kapu1178 at commit 58cfcf943c](https://github.com/DaedalusDock/Gameserver/pull/501)
[#498: 'Use rust_g over byond file write for dynamic setup' by Kapu1178 at commit 446f037ef8](https://github.com/DaedalusDock/Gameserver/pull/498)
[#432: 'Bump rust-g, fix config_error' by francinum at commit 7931dd770c](https://github.com/DaedalusDock/Gameserver/pull/432)
[#508: 'Small tweak to phone icon state handling' by francinum at commit 93ad0d97b9](https://github.com/DaedalusDock/Gameserver/pull/508)
[#524: 'fixes ambience' by Kapu1178 at commit e442c5fb96](https://github.com/DaedalusDock/Gameserver/pull/524)
[#523: 'Brainmed' by Kapu1178 at commit 601bd5490c](https://github.com/DaedalusDock/Gameserver/pull/523)
[#521: 'pressure damage now hurts your ears and eyes' by Kapu1178 at commit 0595db0370](https://github.com/DaedalusDock/Gameserver/pull/521)
[#525: 'Better stack trace code for DCS related things' by Kapu1178 at commit e98016c4f4](https://github.com/DaedalusDock/Gameserver/pull/525)

## Reproduction:
Create a spear to mount a head on (spike head), then try to mount a head, it will not be successful. When you take down the spear by primary clicking you will take it down and spawn a copy of your own head.

The spear is not used during the crafting process either.

This also seems to be able to decapitate the person placing the spike head, but I cannot reproduce this bug

**Comment by Kapu1178** [comment]
Fixed and forgot to link issue
