### ISSUE TITLE
Another Big Medical Report

### ISSUE THREAD

**Issue by Xerkie** [DaedalusDock/daedalusdock#533]
## Testmerges:
[#445: 'Saves more init time + fixes a minor SSshuttle bug' by Kapu1178 at commit e2b9c35c00](https://github.com/DaedalusDock/Gameserver/pull/445)
[#500: 'adds the Voice Changer and more' by Kapu1178 at commit 62e5822486](https://github.com/DaedalusDock/Gameserver/pull/500)
[#505: 'Click-Drag can now be used to consistently manipulate inventories.' by Kapu1178 at commit 41786801f5](https://github.com/DaedalusDock/Gameserver/pull/505)
[#501: 'LITD Fixes' by Kapu1178 at commit 58cfcf943c](https://github.com/DaedalusDock/Gameserver/pull/501)
[#498: 'Use rust_g over byond file write for dynamic setup' by Kapu1178 at commit 446f037ef8](https://github.com/DaedalusDock/Gameserver/pull/498)
[#432: 'Bump rust-g, fix config_error' by francinum at commit 7931dd770c](https://github.com/DaedalusDock/Gameserver/pull/432)
[#508: 'Small tweak to phone icon state handling' by francinum at commit 93ad0d97b9](https://github.com/DaedalusDock/Gameserver/pull/508)
[#524: 'fixes ambience' by Kapu1178 at commit e442c5fb96](https://github.com/DaedalusDock/Gameserver/pull/524)
[#523: 'Brainmed' by Kapu1178 at commit 601bd5490c](https://github.com/DaedalusDock/Gameserver/pull/523)
[#521: 'pressure damage now hurts your ears and eyes' by Kapu1178 at commit 0595db0370](https://github.com/DaedalusDock/Gameserver/pull/521)
[#525: 'Better stack trace code for DCS related things' by Kapu1178 at commit e98016c4f4](https://github.com/DaedalusDock/Gameserver/pull/525)

## Reproduction: Many issues
1: Dylovene, Meralyne, and Alkysine appeared to do pretty much flat-out nothing for a patient. The miner was dosed on well over 100u, nearing 200u, Dylovene, and this did nothing to relieve his toxic damage. Similar with alkysine, and meralyne just didn't heal at all.
2: TG Overdoses. Any overdosed chem has the overdose become "permanent" till the chem is FULLY purged. May be intentional, but doesn't jive very well with brainmed.
3: Anesthetic tanks leak small amounts of N2O into the operating rooms, which are unventilated, leading to N2O buildup.
4: Braindamage doesn't display properly on healthscanners.
5: Health scanners do not display helpful/medical reagents on-scan, like on Bay. May be intentional.
6: Brute Kits are consumed EXTREMELY fast for surgery, and you don't get very many of them, leading to constant repurchases from the machines and running out very quickly if medical has many organ-damaged patients, and there is no Peridaxon to heal minor organ damage quickly.
7: There are no Bonesetters roundstart in the medical operating rooms.
8: Vascular Recouplers do not fit on the medical belt. May be intentional.
9: Braindamage appears to limit your total blood-oxygen levels. May be intentional, but is very wonky.
10: A patient, the aforementioned miner, was at an extreme level of toxin and oxygen damage, with almost all his organs failing, and his brain fading away, was still upright, walking and talking perfectly fine, albeit very slow, not in a deathspiral at all. Persisted for the entire rest of the round. No idea what caused this.
11: A patient had zero pulse and was not breathing according to their surgical Vitals Monitor, yet the defibrillator reported they were not in a "valid state" to be defibbed.
12: A patient had their braindamage completely cured and yet still appeared to display symptoms of severe braindamage, with the TG braindamage talk, slurring and drooling, etc. May have been from multiple traumas, not sure.
13: Smoking was really, really lethal. After chainsmoking a few cigs I was coughing up blood and gasping for air. May be intentional.

**Comment by Jedi-Toothpaste** [comment]
There is also no radium in the chem dispenser, kapu does know this though, just putting it here for posterity
3. they leak because the valve isn't closed again before you put it on the holder
13. please see report #531 for further info
