### ISSUE TITLE
ANY damage can straight up decapitate or remove limbs

### ISSUE THREAD

**Issue by myontasm** [DaedalusDock/daedalusdock#534]
## Round ID:
164

## Reproduction:
I beat myself with a wrench several times in the head to test damage out. Ended up just clocking my head clean off. This also happened with holodeck bees sting.

![image](https://github.com/DaedalusDock/daedalusdock/assets/10575508/9a3e19f9-49f0-4fa9-8d70-97cb98211710)

**Comment by Kapu1178** [comment]
dismemberment formula redone
