### ISSUE TITLE
Screaming due to damage has no cooldown (debatably a feature)

### ISSUE THREAD

**Issue by Spyroshark** [DaedalusDock/daedalusdock#535]
## Testmerges:
https://github.com/DaedalusDock/Gameserver/pull/445
https://github.com/DaedalusDock/Gameserver/pull/500
https://github.com/DaedalusDock/Gameserver/pull/505
https://github.com/DaedalusDock/Gameserver/pull/501
https://github.com/DaedalusDock/Gameserver/pull/498
https://github.com/DaedalusDock/Gameserver/pull/432
https://github.com/DaedalusDock/Gameserver/pull/508
https://github.com/DaedalusDock/Gameserver/pull/524
https://github.com/DaedalusDock/Gameserver/pull/523
https://github.com/DaedalusDock/Gameserver/pull/521
https://github.com/DaedalusDock/Gameserver/pull/525

## The Issue:
![image](https://github.com/DaedalusDock/daedalusdock/assets/35285914/85b1e98f-dd13-406a-ba57-dd34015d397b)
(It's really funny to see *scream be spammed 50 times, but it's very loud and makes chat a mess.)
## Reproduction:
take lots of small hits in quick succession from any source. Bees are in the example, I'd imagine there are other things that would get a similar result.

**Comment by Spyroshark** [comment]
https://github.com/DaedalusDock/daedalusdock/assets/35285914/f2b1c52d-f079-41b9-a9d0-3bd6319bac8e

**Comment by Kapu1178** [comment]
It has a cooldown, but theres a slim chance when you're hit you scream anyway. Not a bug.
