### ISSUE TITLE
Return of the broken helmet flashlights!

### ISSUE THREAD

**Issue by blackwolf602** [DaedalusDock/daedalusdock#559]
## Round ID:
Private testing

## Reproduction:
spawn in a flashlight, try to put it on any helmet wont work.

**Comment by francinum** [comment]
Can you be more specific, What helmet, Is that helmet allowed to have a flashlight on it? Does it have the `/datum/component/seclite_attachable` component?

**Comment by blackwolf602** [comment]
> attachable

Won't be at my pc for two days but I remember it was helmet/sec that was unable to attach flashlights.
