### ISSUE TITLE
Viruses spawn with uncraftable cures

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#572]
Reporting client info:
```Client Information:
BYOND:514.1589
Key:spyroshark
```

## Round ID:
166

## Testmerges:
- [Brainmed](https://github.com/DaedalusDock/Gameserver/pull/523)
- [Browser datums no longer force HTML 4.1](https://github.com/DaedalusDock/Gameserver/pull/549)
- [Enables Life Reference Tracking](https://github.com/DaedalusDock/Gameserver/pull/540)
- [Removes ticket tracking and notification logic](https://github.com/DaedalusDock/Gameserver/pull/539)
- [[PORT] Adds logic to provide leniency for drag clicks (#71082)](https://github.com/DaedalusDock/Gameserver/pull/504)
- [Refactor credits javascript handler](https://github.com/DaedalusDock/Gameserver/pull/558)
- [Experiment: Prevent Qdeleting objects from calling anything that isnt moveToNullspace()](https://github.com/DaedalusDock/Gameserver/pull/555)
- [Kinesis ports](https://github.com/DaedalusDock/Gameserver/pull/561)
- [Data Terminals are now buildable](https://github.com/DaedalusDock/Gameserver/pull/560)
- [Removes ATMO-ECOM INIT, STAT now intercepts.](https://github.com/DaedalusDock/Gameserver/pull/550)
- [Automatic Input Redirection](https://github.com/DaedalusDock/Gameserver/pull/458)
- [ports various missing parts of TG PRs](https://github.com/DaedalusDock/Gameserver/pull/563)

## Reproduction:
The pool of chems that viruses will pick from as their cure has multiple that can't be crafted post-trekchem rework. Some of them can be dispensed by borgs, but others are just completely incurable outside of admin intervention. I know kapu already knows this but I'm putting it up as an issue report so he remembers to fix it.

**Comment by Kapu1178** [comment]
@Spyroshark What chems?
