### ISSUE TITLE
Structure Layering Issue?

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#573]
Reporting client info:
```Client Information:
BYOND:514.1589
Key:ta3370
```

## Round ID:
166

## Testmerges:
- [Brainmed](https://github.com/DaedalusDock/Gameserver/pull/523)
- [Browser datums no longer force HTML 4.1](https://github.com/DaedalusDock/Gameserver/pull/549)
- [Enables Life Reference Tracking](https://github.com/DaedalusDock/Gameserver/pull/540)
- [Removes ticket tracking and notification logic](https://github.com/DaedalusDock/Gameserver/pull/539)
- [[PORT] Adds logic to provide leniency for drag clicks (#71082)](https://github.com/DaedalusDock/Gameserver/pull/504)
- [Refactor credits javascript handler](https://github.com/DaedalusDock/Gameserver/pull/558)
- [Experiment: Prevent Qdeleting objects from calling anything that isnt moveToNullspace()](https://github.com/DaedalusDock/Gameserver/pull/555)
- [Kinesis ports](https://github.com/DaedalusDock/Gameserver/pull/561)
- [Data Terminals are now buildable](https://github.com/DaedalusDock/Gameserver/pull/560)
- [Removes ATMO-ECOM INIT, STAT now intercepts.](https://github.com/DaedalusDock/Gameserver/pull/550)
- [Automatic Input Redirection](https://github.com/DaedalusDock/Gameserver/pull/458)
- [ports various missing parts of TG PRs](https://github.com/DaedalusDock/Gameserver/pull/563)

## Reproduction:
Just prior to shuttle arrival, attempted to put an item in disposals, the disposals spit it out to the side with the trunk pipe becoming visible. Proceeded to try and put a duffelbag on a table, and everything on the table became under the table. I have no gosh darn idea.

**Comment by Kapu1178** [comment]
Needs reproduction
