### ISSUE TITLE
Light replacer thinks it's empty when it's full.

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#625]
Reporting client info:
```Client Information:
BYOND:514.1582
Key:lordlightningchap
```

## Round ID:
168

## Testmerges:
- [Enables Live Reference Tracking](https://github.com/DaedalusDock/Gameserver/pull/540)
- [Experiment: Prevent Qdeleting objects from calling anything that isnt moveToNullspace().](https://github.com/DaedalusDock/Gameserver/pull/555)
- [bleed debug](https://github.com/DaedalusDock/Gameserver/pull/592)
- [Spoken text in chat has a unique color](https://github.com/DaedalusDock/Gameserver/pull/616)
- [fixes & increases SSinput click delay threshold & moves it and averag](https://github.com/DaedalusDock/Gameserver/pull/611)
- [Head Internals](https://github.com/DaedalusDock/Gameserver/pull/606)
- [GPRS PDAs Take 2](https://github.com/DaedalusDock/Gameserver/pull/565)
- [Adds Jinan lore.](https://github.com/DaedalusDock/Gameserver/pull/618)
- [Allows SSPackets to actually hibernate](https://github.com/DaedalusDock/Gameserver/pull/614)
- [IPCs, Health system fixes, Pain fixes, oh my!](https://github.com/DaedalusDock/Gameserver/pull/619)
- [wood and lighting](https://github.com/DaedalusDock/Gameserver/pull/623)

## Reproduction:
I'm not sure if anything was changed that would affect the light replacer, but after placing glass in to refill it (before it was fully empty) it started giving the "The light replacer's refill light blinks red." prompt when trying to fix any light. Even after filling the light replacer entirely the prompt still shows up and doesn't allow any lights to be fixed.

**Comment by francinum** [comment]
Can't replicate. I can't see any holes in the math logic where this could possibly occur. If this reoccurs, post an image of the object's examine output.
