### ISSUE TITLE
Enabling Pumps Through Hotkeys Tries Pulling

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#658]
Reporting client info:
```Client Information:
BYOND:514.1582
Key:lordlightningchap
```

## Round ID:
170

## Testmerges:
- [GPRS PDAs Take 2](https://github.com/DaedalusDock/Gameserver/pull/565)
- [Optimize client rendering](https://github.com/DaedalusDock/Gameserver/pull/638)
- [modlinks](https://github.com/DaedalusDock/Gameserver/pull/655)
- [Mouse pointers](https://github.com/DaedalusDock/Gameserver/pull/654)
- [Necrosis](https://github.com/DaedalusDock/Gameserver/pull/651)
- [Media loading stability improvements](https://github.com/DaedalusDock/Gameserver/pull/650)

## Reproduction:
Very minor bug, using the ctrl+LMB hotkey to interact with an atmos pump will produce a message as if you were trying to pull it even while anchored. Ex. "Unit 1 Head Pressure Pump won't budge!"

**Comment by Kapu1178** [comment]
You can control click pumps to enable them???
