### ISSUE TITLE
The mining office APC not connected with wire

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#667]
Reporting client info:
```Client Information:
BYOND:515.1620
Key:raichitlitchi
```

## Round ID:
171

## Testmerges:
- [Mouse pointers](https://github.com/DaedalusDock/Gameserver/pull/654)
- [Necrosis](https://github.com/DaedalusDock/Gameserver/pull/651)
- [Media loading stability improvements](https://github.com/DaedalusDock/Gameserver/pull/650)
- [Deletes lavaland and everything related to it](https://github.com/DaedalusDock/Gameserver/pull/653)

## Reproduction:
The mining office in this map by station start, Appears to have wires not connected to the APC Itself. Which made me have to connect the APC as an engineer to resolve the power issue not being conncected to external power pretty much.

**Comment by Kapu1178** [comment]
Fixed, forgot to mark
