### ISSUE TITLE
Suit lockers unable to be opened

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#679]
Reporting client info:
```Client Information:
BYOND:514.1589
Key:limed00d
```

## Round ID:
172

## Testmerges:
- [Necrosis](https://github.com/DaedalusDock/Gameserver/pull/651)
- [cleanup grab things](https://github.com/DaedalusDock/Gameserver/pull/670)
- [Fixes being able to move when you shouldn't be able to](https://github.com/DaedalusDock/Gameserver/pull/669)
- [adds none option to ipc shackles](https://github.com/DaedalusDock/Gameserver/pull/668)
- [Refactors hud code, MASSIVELY improves Observe verb.](https://github.com/DaedalusDock/Gameserver/pull/657)
- [modlinks](https://github.com/DaedalusDock/Gameserver/pull/655)
- [Nerfs body throwing](https://github.com/DaedalusDock/Gameserver/pull/677)
- [Asteroid magnet tweaks](https://github.com/DaedalusDock/Gameserver/pull/675)
- [Minor Fixes](https://github.com/DaedalusDock/Gameserver/pull/678)

## Reproduction:
Suit lockers are brokey. TGUI issue, or are spaceman hands so weak? Who knows!

**Comment by Kapu1178** [comment]
Fixed, PR bug.
