### ISSUE TITLE
There seems to be a missplaced light fixture at the bottom right solar maints.

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#682]
Reporting client info:
```Client Information:
BYOND:514.1589
Key:kondafairydragon
```

## Round ID:
172

## Testmerges:
- [Necrosis](https://github.com/DaedalusDock/Gameserver/pull/651)
- [cleanup grab things](https://github.com/DaedalusDock/Gameserver/pull/670)
- [Fixes being able to move when you shouldn't be able to](https://github.com/DaedalusDock/Gameserver/pull/669)
- [adds none option to ipc shackles](https://github.com/DaedalusDock/Gameserver/pull/668)
- [Refactors hud code, MASSIVELY improves Observe verb.](https://github.com/DaedalusDock/Gameserver/pull/657)
- [modlinks](https://github.com/DaedalusDock/Gameserver/pull/655)
- [Nerfs body throwing](https://github.com/DaedalusDock/Gameserver/pull/677)
- [Asteroid magnet tweaks](https://github.com/DaedalusDock/Gameserver/pull/675)
- [Minor Fixes](https://github.com/DaedalusDock/Gameserver/pull/678)

## Reproduction:
Missplaced light fixture, like i already said, it is just hovering in the middle of the tile, not connected to any wall

**Comment by francinum** [comment]
I have been unable to remotely track this down. If it's still there next test maybe someone will provide a more specific report.
