### ISSUE TITLE
AI manifest speech does not work

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#697]
Reporting client info:
```Client Information:
BYOND:514.1589
Key:cenrus
```

## Round ID:
175

## Testmerges:
- [Necrosis](https://github.com/DaedalusDock/Gameserver/pull/651)
- [modlinks](https://github.com/DaedalusDock/Gameserver/pull/655)
- [minor breath changes](https://github.com/DaedalusDock/Gameserver/pull/694)
- [Jukebox update](https://github.com/DaedalusDock/Gameserver/pull/692)

## Reproduction:
Right clicking a holopad as the AI and speaking usually relays your speech into the hologram projection, but it hasn't been working during the test.

**Comment by Kapu1178** [comment]
You use the `:h` prefix to talk during a holocall.
