### ISSUE TITLE
chem fridges won't accept hypovials

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#714]
Reporting client info:
```Client Information:
BYOND:514.1589
Key:yyzsong
```

## Round ID:
176

## Testmerges:
- [Necrosis](https://github.com/DaedalusDock/Gameserver/pull/651)
- [WALL THEFT](https://github.com/DaedalusDock/Gameserver/pull/712)
- [Cartchem (Port)](https://github.com/DaedalusDock/Gameserver/pull/711)
- [Ma Bell Rises From The Grave](https://github.com/DaedalusDock/Gameserver/pull/710)
- [Try to fix spacedrift](https://github.com/DaedalusDock/Gameserver/pull/708)
- [sprinting in space no more](https://github.com/DaedalusDock/Gameserver/pull/707)
- [bugsbugsbugs](https://github.com/DaedalusDock/Gameserver/pull/706)
- [Moveloop maintenance ports](https://github.com/DaedalusDock/Gameserver/pull/687)

## Reproduction:
see title

**Comment by francinum** [comment]
Consistent with Skyrat's implementation, at least from a read of the code.
