### ISSUE TITLE
Roundstart uplink implant cannot be activated/used

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#726]
Reporting client info:
```Client Information:
BYOND:514.1589
Key:myontasm
```

## Round ID:
177

## Testmerges:
- [Cartchem (Port)](https://github.com/DaedalusDock/Gameserver/pull/711)
- [Moveloop maintenance ports](https://github.com/DaedalusDock/Gameserver/pull/687)
- [Reactions correctly respect the `REACTION_HEAT_ARBITARY` flag](https://github.com/DaedalusDock/Gameserver/pull/724)
- [Dumb cables](https://github.com/DaedalusDock/Gameserver/pull/621)
- [micro optimize bucket join](https://github.com/DaedalusDock/Gameserver/pull/720)

## Reproduction:
Title, seems like I can't click the uplink "Activate" action on the hud. I dunno if it's an issue with the implant overall or just the roundstart option one, but I'm having issues with the latter.

**Comment by Kapu1178** [comment]
i think i fixed this
