### ISSUE TITLE
Cannot use radio even after a grab.

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#727]
Reporting client info:
```Client Information:
BYOND:514.1582
Key:lordlightningchap
```

## Round ID:
177

## Testmerges:
- [Cartchem (Port)](https://github.com/DaedalusDock/Gameserver/pull/711)
- [Moveloop maintenance ports](https://github.com/DaedalusDock/Gameserver/pull/687)
- [Reactions correctly respect the `REACTION_HEAT_ARBITARY` flag](https://github.com/DaedalusDock/Gameserver/pull/724)
- [Dumb cables](https://github.com/DaedalusDock/Gameserver/pull/621)
- [micro optimize bucket join](https://github.com/DaedalusDock/Gameserver/pull/720)

## Reproduction:
When in a potted plant, I escaped an aggro grab by resting then sliding under someone. I am out of the grab but I think it didn't update a flag or something, as I am unable to use my radio.

**Comment by Kapu1178** [comment]
Somehow the TRAIT_AGGRESSIVE_GRAB stuck even though the grab was garbage collected. Odd.

**Comment by Kapu1178** [comment]
Reopen if reproduced
