### ISSUE TITLE
Defibrillators not working

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#768]
Reporting client info:
```Client Information:
BYOND:514.1589
Key:ddanpointman
```

## Round ID:
179

## Testmerges:
- [Adds an onscreen click timer](https://github.com/DaedalusDock/Gameserver/pull/732)
- [Potato Contents + center loaded maps](https://github.com/DaedalusDock/Gameserver/pull/763)
- [Mod suits runtime fix](https://github.com/DaedalusDock/Gameserver/pull/760)

## Reproduction:
On today (14-01-2024)'s playtest, none of the defibrilaltors were working. I and a few other players were not able to dual-wield the paddles,, thus rending them unoperable

**Comment by Kapu1178** [comment]
Defibrillators aren't broken, people were just unaware of the wield key.
