### ISSUE TITLE
'Open Webmap' has an invalid link

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#792]
Reporting client info:
```Client Information:
BYOND:514.1589
Key:gonenoculer5
```

## Round ID:
182

## Testmerges:
- [Adds an onscreen click timer](https://github.com/DaedalusDock/Gameserver/pull/732)
- [Mod suits runtime fix](https://github.com/DaedalusDock/Gameserver/pull/760)
- [Fixes and optimizations](https://github.com/DaedalusDock/Gameserver/pull/771)
- [minor fixes](https://github.com/DaedalusDock/Gameserver/pull/770)
- [Removes name setting from Life(), adds `set_real_name()`](https://github.com/DaedalusDock/Gameserver/pull/766)
- [Ghost Content and Spooky Things](https://github.com/DaedalusDock/Gameserver/pull/780)
- [Projectilesimprovement](https://github.com/DaedalusDock/Gameserver/pull/782)

## Reproduction:
The open webmap button redirects to an incorrect namespace for the map, the valid link is: https://affectedarc07.github.io/SS13WebMap/DaedalusDock/DaedalusMeta/

**Comment by Kapu1178** [comment]
Not a bug with the ss13 code

**Comment by francinum** [comment]
It is, *technically*, but it only occurs if the fallback config is loaded, which shouldn't occur on live or any actually in use server.
