### ISSUE TITLE
Achievements Menu has invalid achievements

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#793]
Reporting client info:
```Client Information:
BYOND:514.1589
Key:gonenoculer5
```

## Round ID:
182

## Testmerges:
- [Adds an onscreen click timer](https://github.com/DaedalusDock/Gameserver/pull/732)
- [Mod suits runtime fix](https://github.com/DaedalusDock/Gameserver/pull/760)
- [Fixes and optimizations](https://github.com/DaedalusDock/Gameserver/pull/771)
- [minor fixes](https://github.com/DaedalusDock/Gameserver/pull/770)
- [Removes name setting from Life(), adds `set_real_name()`](https://github.com/DaedalusDock/Gameserver/pull/766)
- [Ghost Content and Spooky Things](https://github.com/DaedalusDock/Gameserver/pull/780)
- [Projectilesimprovement](https://github.com/DaedalusDock/Gameserver/pull/782)

## Reproduction:
The 'Check Achievements' verb has achievements that are no longer valid (such as Lavaland achievements) that should have been cleaned up in the LL removal.

**Comment by francinum** [comment]
I'm mixed on this one, The achievements are still technically tracked and we have that data on the serverside.
