### ISSUE TITLE
IPCs can get addicted to smoking

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#808]
Reporting client info:
```Client Information:
BYOND:514.1589
Key:myontasm
```

## Round ID:
184

## Testmerges:
- [Ghost Content and Spooky Things](https://github.com/DaedalusDock/Gameserver/pull/780)
- [Fracture changes](https://github.com/DaedalusDock/Gameserver/pull/800)
- [Lighting refactor](https://github.com/DaedalusDock/Gameserver/pull/801)
- [Kapuconomy Part 2 of X](https://github.com/DaedalusDock/Gameserver/pull/802)
- [Throwing tweaks](https://github.com/DaedalusDock/Gameserver/pull/806)

## Reproduction:
... Which doesn't make sense as they don't have a mouth to inhale the smoke with! So realistically all they  SHOULD achieve is a lit stinker burning away on their monitor face, but as it turns out, they still inhale the smoke.

**Comment by Kapu1178** [comment]
feature
