### ISSUE TITLE
Text-Bubble Escape Issue

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#836]
Reporting client info:
```Client Information:
BYOND:515.1631
Key:spaghettibirb
```

## Round ID:
186

## Testmerges:
- [Lighting refactor](https://github.com/DaedalusDock/Gameserver/pull/801)
- [glue pr](https://github.com/DaedalusDock/Gameserver/pull/831)
- [Tgports3](https://github.com/DaedalusDock/Gameserver/pull/817)
- [Refactors Obscurity, caches `flags_inv`. Improves equip/unequip code.](https://github.com/DaedalusDock/Gameserver/pull/826)
- [Storage Cleanup](https://github.com/DaedalusDock/Gameserver/pull/804)
- [(needs 515.1624) Bodypart code cleanup via 515](https://github.com/DaedalusDock/Gameserver/pull/722)

## Reproduction:
Opening  a text bot (T) to speak, then pressing escape. Result: Speech bubble will persist.

Goes away after pressing opening a new 'say' and entering it.

**Comment by Kapu1178** [comment]
Unfixable
