### ISSUE TITLE
'Look Closer?' examine is broken

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#837]
Reporting client info:
```Client Information:
BYOND:515.1631
Key:gonenoculer5
```

## Round ID:
186

## Testmerges:
- [Lighting refactor](https://github.com/DaedalusDock/Gameserver/pull/801)
- [glue pr](https://github.com/DaedalusDock/Gameserver/pull/831)
- [Tgports3](https://github.com/DaedalusDock/Gameserver/pull/817)
- [Refactors Obscurity, caches `flags_inv`. Improves equip/unequip code.](https://github.com/DaedalusDock/Gameserver/pull/826)
- [Storage Cleanup](https://github.com/DaedalusDock/Gameserver/pull/804)
- [(needs 515.1624) Bodypart code cleanup via 515](https://github.com/DaedalusDock/Gameserver/pull/722)

## Reproduction:
When trying to check someones flavortext, the examine for it is broken.

**Comment by Kapu1178** [comment]
duplicate

**Comment by francinum** [comment]
Duplicate of #767
