### ISSUE TITLE
Vital Monitors Beep Without Patients

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#865]
Reporting client info:
```Client Information:
BYOND:515.1631
Key:pitaden
```

## Round ID:
191

## Testmerges:
- [Temporary canRecall fix](https://github.com/DaedalusDock/Gameserver/pull/862)
- [improves investigate_log](https://github.com/DaedalusDock/Gameserver/pull/854)
- [Refactor cuffing](https://github.com/DaedalusDock/Gameserver/pull/830)
- [Impliments rgb2num() in all color procs](https://github.com/DaedalusDock/Gameserver/pull/819)
- [Changes to atom integrity](https://github.com/DaedalusDock/Gameserver/pull/863)
- [Autocodex](https://github.com/DaedalusDock/Gameserver/pull/864)

## Reproduction:
If a patient is placed on an operating table, then removed from it, the vital monitor will still beep even if the patient is nowhere near it.

**Comment by Kapu1178** [comment]
fixed
