### ISSUE TITLE
security marshal can't send announcement from bridge comms console

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#873]
Reporting client info:
```Client Information:
BYOND:515.1633
Key:spyroshark
```

## Round ID:
192

## Testmerges:
- [Temporary canRecall fix](https://github.com/DaedalusDock/Gameserver/pull/862)
- [improves investigate_log](https://github.com/DaedalusDock/Gameserver/pull/854)
- [Refactor cuffing](https://github.com/DaedalusDock/Gameserver/pull/830)
- [Fixes two-handed items and runtimes](https://github.com/DaedalusDock/Gameserver/pull/869)
- [grab fixes](https://github.com/DaedalusDock/Gameserver/pull/868)
- [[WIP] mars sec](https://github.com/DaedalusDock/Gameserver/pull/856)

## Reproduction:
yeah

**Comment by francinum** [comment]
Only the captain can. Others use the request console.
