### ISSUE TITLE
Xenobio gets no power on Theseus Station

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#878]
Reporting client info:
```Client Information:
BYOND:515.1633
Key:hymh
```

## Round ID:
193

## Testmerges:
- [Temporary canRecall fix](https://github.com/DaedalusDock/Gameserver/pull/862)
- [improves investigate_log](https://github.com/DaedalusDock/Gameserver/pull/854)
- [Refactor cuffing](https://github.com/DaedalusDock/Gameserver/pull/830)
- [Fixes two-handed items and runtimes](https://github.com/DaedalusDock/Gameserver/pull/869)
- [grab fixes](https://github.com/DaedalusDock/Gameserver/pull/868)
- [[WIP] mars sec](https://github.com/DaedalusDock/Gameserver/pull/856)

## Reproduction:
Pretty much exactly what it says on the tin. Ahelped about it to make sure it wasn't an IC issue and was clarified that it was not.

**Comment by francinum** [comment]
xenobio has been taken out behind the chemical shed.
