### ISSUE TITLE
Pull HUD Icon in the wrong place

### ISSUE THREAD

**Issue by Jedi-Toothpaste** [DaedalusDock/daedalusdock#894]
## Testmerges:
#862 #854 #856 #892 #893 #883 

## Reproduction:
When pulling an item the HUD icon is placed incorrectly below where Energy is
![image](https://github.com/DaedalusDock/daedalusdock/assets/53096233/be65ac93-5df8-4f5f-aa35-4a1e60aafe41)

**Comment by Kapu1178** [comment]
testmerge bug
