### ISSUE TITLE
Books show raw HTML

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#932]
Reporting client info:
```Client Information:
BYOND:515.1633
Key:cenrus
```

## Round ID:
201

## Testmerges:
- [Adds a Guest Mode](https://github.com/DaedalusDock/Gameserver/pull/917)
- [Split brained tgui](https://github.com/DaedalusDock/Gameserver/pull/909)
- [Debug reboot failures](https://github.com/DaedalusDock/Gameserver/pull/923)
- [Bumps byond version to 515.1637](https://github.com/DaedalusDock/Gameserver/pull/931)

## Reproduction:
Library books contain raw HTML code, such as spans and headers which makes them much harder to read.

**Comment by Kapu1178** [comment]
Not a bug
