### ISSUE TITLE
Random disposal segment in space

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#941]
Reporting client info:
```Client Information:
BYOND:515.1634
Key:gonenoculer5
```

## Round ID:
202

## Testmerges:
- [Debug reboot failures](https://github.com/DaedalusDock/Gameserver/pull/923)
- [Bumps byond version to 515.1637](https://github.com/DaedalusDock/Gameserver/pull/931)
- [Enables Live Reference Tracking](https://github.com/DaedalusDock/Gameserver/pull/540)
- [The Split](https://github.com/DaedalusDock/Gameserver/pull/926)

## Reproduction:
https://i.imgur.com/wlw9wJU.png 

East of the recycler is a random girder and stray segment of disposal pipe.

**Comment by francinum** [comment]
It's detailing, Considering the inclusion of broken pipes.
