### ISSUE TITLE
Ampcheck UI Crashing TGUI

### ISSUE THREAD

**Issue by DaedalusDock-Services** [DaedalusDock/daedalusdock#978]
Reporting client info:
```Client Information:
BYOND:514.1582
Key:lordlightningchap
```

## Round ID:
206

## Testmerges:
- [Debug reboot failures](https://github.com/DaedalusDock/Gameserver/pull/923)
- [Bumps byond version to 515.1637](https://github.com/DaedalusDock/Gameserver/pull/931)
- [Enables Live Reference Tracking](https://github.com/DaedalusDock/Gameserver/pull/540)
- [Temporary canRecall fix](https://github.com/DaedalusDock/Gameserver/pull/862)
- [SQLite Codex Optimization](https://github.com/DaedalusDock/Gameserver/pull/963)
- [Improve modsuit code](https://github.com/DaedalusDock/Gameserver/pull/976)
- [Tgooey Restyle](https://github.com/DaedalusDock/Gameserver/pull/969)

## Reproduction:
Ampcheck engineering program crashes TGUI upon opening.

**Comment by Kapu1178** [comment]
NtosPowerMonitor.jsx

**Comment by francinum** [comment]
Not Fixed.
